### ISSUE TITLE
writing in jsng shell is very slow sometimes 

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-ng#330] opened 2020-06-18 10:19 UTC

**Comment by abom** [comment] 2020-06-29 13:52
Seems like it's the result of mixing asyncio (used by ptpython/shell) with gevent.

After trying to disable gevent monkey-patching, the slowness is gone.

**Comment by xmonader** [comment] 2021-01-13 09:40
duplicate of https://github.com/threefoldtech/js-ng/issues/533

**Closed** 2021-01-13 09:40 UTC
Labels: type_bug
