### ISSUE TITLE
got a segmentation fault while trying to login to jsng shell 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-ng#458] opened 2020-09-22 15:03 UTC
- Got a segmentation fault while trying to login to jsng shell (jsng has been installed on docker)

**Commit_ID** abbeba613319e6ff3b02143a6ba18310575ca266 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/93900288-7e0a1b00-fcf5-11ea-8564-0940d4c51cf9.png)

**Comment by abom** [comment] 2020-09-22 17:24
Cannot reproduce, tried with this image again https://hub.docker.com/r/threefoldtech/js-ng

**Comment by abom** [comment] 2020-09-22 17:49
I can reproduce on a fresh manual installation using poetry on `ubuntu:19` container.

```
(js-sdk-w2FClMcC-py3.7) root@5c2a4182417d:/js-sdk# jsng
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
Segmentation fault (core dumped)
(js-sdk-w2FClMcC-py3.7) root@5c2a4182417d:/js-sdk# 
```

**Comment by abom** [comment] 2020-09-22 17:52
Some related issues in other projects suggest downgrading `greenlet`, main issue is here https://github.com/gevent/gevent/issues/1260.

**Comment by abom** [comment] 2020-09-22 18:08
Now this issue should not happen in `js-ng` as long as we install without poetry update (current locked deps are ok).

But in the manual installation for `js-sdk`, we do `poetry update`, which should not happen, as we already track a poetry.lock file, people do not need to do this, as this might produce an installations with dependencies we didn't test, with something like the current greenlet broken ABI for python3.7 on ubuntu 19.10 (what I tests).

I suggest we close this here, and re-open a new issue in `js-sdk` repository to set current greenlet version to `greenlet==0.4.16` (as it works for me), and also push an updated and working poetry.lock file, and remove `poetry update` step from all installation instructions as this need to be done by maintainers only.

**Comment by abom** [comment] 2020-09-22 18:11
Current working versions in `js-ng` environemnt:


```
gevent==1.4.0
greenlet==0.4.16
```

Current broken versions in `js-sdk` environment:


```
gevent==1.4.0  
greenlet==0.4.17                                                            
```

**Comment by abom** [comment] 2020-09-23 10:17
Related issue:

https://github.com/python-greenlet/greenlet/issues/178

**Comment by abom** [comment] 2020-09-23 10:27
They yanked the broken version for now:

> I yanked 0.4.17 for the time being.

https://github.com/python-greenlet/greenlet/issues/178#issuecomment-696723056

**Comment by rkhamis** [comment] 2020-12-23 10:53
closed in favor of https://github.com/threefoldtech/js-sdk/issues/1713

**Closed by rkhamis** 2020-12-23 10:53 UTC
Labels: type_bug
